global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@devops-app.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/'
    send_resolved: true

- name: 'email'
  email_configs:
  - to: 'admin@devops-app.com'
    subject: 'DevOps Application Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Description: {{ .CommonAnnotations.description }}
      Instance: {{ .CommonLabels.instance }}
      Status: {{ .Status }}
      Time: {{ .StartsAt }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
